# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-23 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0002_customer_capital_one_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='outstanding_requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_debtor', to='handle.Customer')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_issuer', to='handle.Customer')),
            ],
        ),
    ]
