# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-23 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0003_outstanding_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pin',
            field=models.CharField(max_length=4),
        ),
    ]
